spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:17254/NEAR
    username: root
    password: test
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      password: password
      port: 16697
  config:
    import:
      - classpath:/application-social.yml
      - classpath:/application-aws.yml
      - classpath:/application-ai.yml
swyp:
  jwt:
    secret: fJm76UJ3g8JL5P9tM3vUZbpuNDKVwGD8RQeMbwu2T15iZpvTM0LQCqERiXqK4Xc0
    access-token-validity-in-milli-seconds: 86400000 # 1일
    refresh-token-validity-in-days: 7 # 7일
  fcm:
    enabled: true
    credentials-path: classpath:firebase.json